# Generated by Django 6.0.7 on 2026-07-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="credit_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=10000.0,
                help_text="Maximum outstanding balance allowed for Net terms B2B billing.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="outstanding_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Current total amount of unpaid monthly invoices.",
                max_digits=12,
            ),
        ),
    ]
