# Generated by Django 6.0.7 on 2026-07-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_company_credit_limit_company_outstanding_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Primary contact phone number.",
                max_length=20,
                null=True,
            ),
        ),
    ]
