# Generated by Django 6.0.7 on 2026-07-13 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "unit_of_measure",
                    models.CharField(
                        help_text="e.g., 50lb Bag, Case of 6, Gallon", max_length=50
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Standard wholesale price rule fallback.",
                        max_digits=12,
                    ),
                ),
                ("stock_quantity", models.IntegerField(default=0)),
                ("is_available", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Master Product",
                "verbose_name_plural": "Master Products",
                "ordering": ["sku"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Processing"),
                            ("APPROVED", "Approved by Logistics"),
                            ("SHIPPED", "Out for Delivery"),
                            ("DELIVERED", "Fulfillment Complete"),
                            ("CANCELLED", "Void / Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("delivery_address_snapshot", models.TextField()),
                ("sales_tax_id_snapshot", models.CharField(max_length=50)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="location_orders",
                        to="accounts.companylocation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placed_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Commercial Purchase Order",
                "verbose_name_plural": "Commercial Purchase Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("price_paid", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="products.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historical_sales",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Line Item",
                "verbose_name_plural": "Transaction Line Items",
            },
        ),
        migrations.CreateModel(
            name="UserCustomPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "negotiated_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_prices",
                        to="accounts.company",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_custom_prices",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corporate Contract Price",
                "verbose_name_plural": "Corporate Contract Prices",
                "unique_together": {("company", "product")},
            },
        ),
        migrations.CreateModel(
            name="ZipCodePricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zip_code", models.CharField(db_index=True, max_length=10)),
                (
                    "regional_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zip_prices",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regional Zip Price Rule",
                "verbose_name_plural": "Regional Zip Price Rules",
                "unique_together": {("zip_code", "product")},
            },
        ),
    ]
