# Generated by Django 6.0.7 on 2026-07-13 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_category_product_image_product_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogisticsWebhookTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Target URL for B2B dispatch notifications.",
                        max_length=500,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Logistics Webhook Target",
                "verbose_name_plural": "Logistics Webhook Targets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CSVImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Completed Successfully"),
                            ("PARTIAL", "Completed with Errors"),
                            ("FAILED", "Failed Entirely"),
                        ],
                        default="SUCCESS",
                        max_length=15,
                    ),
                ),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("CATALOG", "Product Inventory Catalog"),
                            ("REGIONAL", "Regional ZIP Pricing Grid"),
                            ("CONTRACT", "Corporate Contract Pricing"),
                        ],
                        max_length=15,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CSV Import Audit Log",
                "verbose_name_plural": "CSV Import Audit Logs",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="CSVImportRowError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField()),
                ("row_data", models.TextField(help_text="Original CSV row content.")),
                ("error_message", models.TextField()),
                (
                    "import_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="row_errors",
                        to="products.csvimportlog",
                    ),
                ),
            ],
            options={
                "verbose_name": "CSV Row Import Error",
                "verbose_name_plural": "CSV Row Import Errors",
                "ordering": ["line_number"],
            },
        ),
    ]
