# Generated by Django 6.0.7 on 2026-07-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_logisticswebhooktarget_csvimportlog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZipCodeRouteRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(db_index=True, max_length=10, unique=True),
                ),
                (
                    "delivery_days",
                    models.CharField(
                        default="1,2,3,4,5,6,7",
                        help_text="Comma-separated ISO weekdays (1=Monday, 7=Sunday).",
                        max_length=50,
                    ),
                ),
                (
                    "cutoff_time",
                    models.TimeField(
                        default="16:00:00",
                        help_text="Daily order cut-off time (24h format). Past this, shipment shifts to the next route day.",
                    ),
                ),
            ],
            options={
                "verbose_name": "ZIP Code Delivery Route Rule",
                "verbose_name_plural": "ZIP Code Delivery Route Rules",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_date",
            field=models.DateField(
                blank=True, help_text="Scheduled route shipment date.", null=True
            ),
        ),
    ]
