# Generated by Django 6.0.7 on 2026-07-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_zipcoderouterule_order_delivery_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical Delay"),
                        ],
                        default="WARNING",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "System Alert",
                "verbose_name_plural": "System Alerts",
                "ordering": ["-created_at"],
            },
        ),
    ]
