# Generated by Django 6.0.7 on 2026-07-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_systemalert"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("NET_30", "Net 30 Terms"),
                    ("CREDIT_CARD", "Credit / Debit Card"),
                    ("ACH", "ACH Bank Transfer"),
                ],
                db_index=True,
                default="NET_30",
                max_length=20,
            ),
        ),
    ]
