"""
Django settings for core_backend project.

Generated by 'django-admin startproject' using Django 6.0.7.
Production-grade configuration mapping enterprise JWTs and B2B organizational layers.
"""

import os
from pathlib import Path
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Explicitly open host listening parameters to support local phone emulator network requests
ALLOWED_HOSTS = ['*']


# ==============================================================================
# B2B CUSTOM USER MODEL CONFIGURATION
# ==============================================================================
# Point Django's core authentication systems directly to our relational user model
AUTH_USER_MODEL = 'accounts.UserProfile'


# ==============================================================================
# DJANGO REST FRAMEWORK & SIMPLEJWT CONFIGURATION
# ==============================================================================
REST_FRAMEWORK = {
    # Mandate that incoming REST API packets undergo cryptographic JWT authentication checks
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # Globally lock down all views; individual endpoints will explicitly bypass this using permissions
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Rotational JWT Performance Policies for Desktop & Mobile Client Enclaves
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),   # Short lifespans minimize hijack vulnerabilities
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),     # Long lifespans preserve persistent mobile app sessions
    'ROTATE_REFRESH_TOKENS': True,                    # Issues a unique refresh token on every lifecycle usage
    'BLACKLIST_AFTER_ROTATION': True,                 # Instantly invalidates used refresh keys in the database
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),                 # Flutter clients pass headers as: 'Authorization: Bearer <JWT>'
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}


# ==============================================================================
# COMMUNICATION & LOGISTICS SYSTEMS
# ==============================================================================
# Outputs all recovery and transaction confirmation email text channels directly into the running server terminal
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# ==============================================================================
# CORS CROSS-ORIGIN CONNECTIVITY PARADIGMS
# ==============================================================================
# Allow cross-origin mobile API hits locally across network emulators and local Wi-Fi bridges
CORS_ALLOW_ALL_ORIGINS = True 


# ==============================================================================
# FILE STORAGE LOGISTICS (COMPLIANCE CERTIFICATES & AUDITING EXEMPTIONS)
# ==============================================================================
# Dictates where physical PDF resale certificates are saved on the server hard drive
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# ==============================================================================
# INSTALLED APPLICATIONS (MIDDLE-LAYERS & CUSTOM MODULE BLUE-PRINTS)
# ==============================================================================
INSTALLED_APPS = [
    # Core Native Framework modules
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party extensions
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist', # Required to support the 'BLACKLIST_AFTER_ROTATION' paradigm
    'corsheaders',

    # Specialized B2B internal functional modules
    'accounts.apps.AccountsConfig',
    'products.apps.ProductsConfig',
]

UNFOLD = {
    "SITE_TITLE": "ZEEE Admin Dashboard",
    "SITE_HEADER": "ZEEE Operations Center",
    "SITE_SYMBOL": "bolt",
    "SHOW_HISTORY": True,
    "SHOW_SIDEBAR_FILTER": True,
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Warehouse Logistics",
                "separator": True,
                "items": [
                    {
                        "title": "Dispatcher Portal",
                        "icon": "local_shipping",
                        "link": "/dispatcher/",
                    }
                ]
            }
        ]
    }
}


# ==============================================================================
# MIDDLEWARE ENGINE TIMELINES
# ==============================================================================
MIDDLEWARE = [
    # CRITICAL: Precedes everything to check network origin compliance before routing requests
    'corsheaders.middleware.CorsMiddleware',
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core_backend.urls'


# ==============================================================================
# GRAPHICAL UI TEMPLATE ENGINE LAYER
# ==============================================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # DIRS now maps directly to a central structural template path wrapper inside the backend folder
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core_backend.wsgi.application'


# ==============================================================================
# TRANSACTING ENVIRONMENT DATABASE ENGINES
# ==============================================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        # Pull database parameters dynamically from the hidden environment file
        'NAME': config('DB_NAME', default='wholesale_db'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# ==============================================================================
# SECURE ALGORITHMIC SECURITY CREDENTIAL AUDITORS
# ==============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ==============================================================================
# REGIONAL SETTING AND GLOBALIZATION PARAMETERS
# ==============================================================================
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'